export const carData = {
  hatchback: [
    { carName: "Maruti Suzuki Swift", carImage: "./image/swift.jpg" },
    { carName: "Hyundai i20", carImage: "./image/i20.jpg" },
    { carName: "Tata Altroz", carImage: "./image/altroz.jpg" },
    { carName: "Maruti Suzuki Baleno", carImage: "./image/baleno.jpg" },
    { carName: "Hyundai Grand i10 Nios", carImage: "./image/nios.jpg" },
    { carName: "Honda Jazz", carImage: "./image/jazz.jpg" },
    { carName: "Volkswagen Polo", carImage: "./image/polo.jpg" },
    { carName: "Ford Figo", carImage: "./image/figo.jpg" },
    { carName: "Renault Kwid", carImage: "./image/kwid.jpg" },
    { carName: "Tata Tiago", carImage: "./image/tiago.jpg" },
  ],
  sedan: [
    { carName: "Honda City", carImage: "./image/city.jpg" },
    { carName: "Maruti Suzuki Dzire", carImage: "./image/dzire.jpg" },
    { carName: "Hyundai Verna", carImage: "./image/verna.jpg" },
    { carName: "Skoda Rapid", carImage: "./image/rapid.jpg" },
    { carName: "Toyota Yaris", carImage: "./image/yaris.jpg" },
    { carName: "Volkswagen Vento", carImage: "./image/vento.jpg" },
    { carName: "Tata Tigor", carImage: "./image/tigor.jpg" },
    { carName: "Honda Amaze", carImage: "./image/amaze.jpg" },
    { carName: "Hyundai Aura", carImage: "./image/aura.jpg" },
    { carName: "Skoda Slavia", carImage: "./image/slavia.jpg" },
  ],
  suv: [
    { carName: "Hyundai Creta", carImage: "./image/creta.jpg" },
    { carName: "Kia Seltos", carImage: "./image/seltos.jpg" },
    { carName: "Tata Nexon", carImage: "./image/nexon.jpg" },
    { carName: "Mahindra XUV700", carImage: "./image/xuv700.jpg" },
    { carName: "Maruti Suzuki Vitara Brezza", carImage: "./image/brezza.jpg" },
    { carName: "Toyota Fortuner", carImage: "./image/fortuner.jpg" },
    { carName: "Ford EcoSport", carImage: "./image/ecosport.jpg" },
    { carName: "MG Hector", carImage: "./image/hector.jpg" },
    { carName: "Mahindra Thar", carImage: "./image/thar.jpg" },
    { carName: "Renault Duster", carImage: "./image/duster.jpg" },
  ],
  mpv: [
    { carName: "Toyota Innova Crysta", carImage: "./image/innova.jpg" },
    { carName: "Maruti Suzuki Ertiga", carImage: "./image/ertiga.jpg" },
    { carName: "Mahindra Marazzo", carImage: "./image/marazzo.jpg" },
    { carName: "Renault Triber", carImage: "./image/triber.jpg" },
    { carName: "Kia Carens", carImage: "./image/carens.jpg" },
    { carName: "Mahindra Xylo", carImage: "./image/xylo.jpg" },
    { carName: "Maruti Suzuki XL6", carImage: "./image/xl6.jpg" },
    { carName: "Honda BR-V", carImage: "./image/brv.jpg" },
    { carName: "Datsun GO+", carImage: "./image/goplus.jpg" },
    { carName: "Toyota Vellfire", carImage: "./image/vellfire.jpg" },
  ],
  ev: [
    { carName: "Tata Nexon EV", carImage: "./image/nexon_ev.jpg" },
    { carName: "MG ZS EV", carImage: "./image/zs_ev.jpg" },
    { carName: "Hyundai Kona Electric", carImage: "./image/kona.jpg" },
    { carName: "Tata Tigor EV", carImage: "./image/tigor_ev.jpg" },
    { carName: "Mahindra eVerito", carImage: "./image/everito.jpg" },
    { carName: "BYD e6", carImage: "./image/e6.jpg" },
    { carName: "Jaguar I-PACE", carImage: "./image/ipace.jpg" },
    { carName: "Audi e-tron", carImage: "./image/etron.jpg" },
    { carName: "Mercedes-Benz EQC", carImage: "./image/eqc.jpg" },
    { carName: "Nissan Leaf", carImage: "./image/leaf.jpg" },
  ],
  luxury: [
    { carName: "Mercedes-Benz S-Class", carImage: "./image/sclass.jpg" },
    { carName: "BMW 7 Series", carImage: "./image/7series.jpg" },
    { carName: "Audi A8", carImage: "./image/a8.jpg" },
    { carName: "Jaguar XJ", carImage: "./image/xj.jpg" },
    { carName: "Lexus LS", carImage: "./image/ls.jpg" },
    { carName: "Volvo S90", carImage: "./image/s90.jpg" },
    { carName: "Porsche Panamera", carImage: "./image/panamera.jpg" },
    { carName: "Bentley Continental GT", carImage: "./image/continental.jpg" },
    { carName: "Rolls-Royce Ghost", carImage: "./image/ghost.jpg" },
    { carName: "Maserati Quattroporte", carImage: "./image/quattroporte.jpg" },
  ],
  sports: [
    { carName: "Porsche 911", carImage: "./image/911.jpg" },
    { carName: "Chevrolet Corvette", carImage: "./image/corvette.jpg" },
    { carName: "Ford Mustang", carImage: "./image/mustang.jpg" },
    { carName: "Audi R8", carImage: "./image/r8.jpg" },
    { carName: "Nissan GT-R", carImage: "./image/gtr.jpg" },
    { carName: "BMW M4", carImage: "./image/m4.jpg" },
    { carName: "Ferrari 488", carImage: "./image/488.jpg" },
    { carName: "Lamborghini Huracan", carImage: "./image/huracan.jpg" },
    { carName: "Aston Martin Vantage", carImage: "./image/vantage.jpg" },
    { carName: "McLaren 720S", carImage: "./image/720s.jpg" },
  ],
  crossover: [
    { carName: "Hyundai Venue", carImage: "./image/venue.jpg" },
    { carName: "Kia Sonet", carImage: "./image/sonet.jpg" },
    { carName: "Nissan Kicks", carImage: "./image/kicks.jpg" },
    { carName: "Maruti Suzuki S-Cross", carImage: "./image/scross.jpg" },
    { carName: "Renault Kiger", carImage: "./image/kiger.jpg" },
    { carName: "Honda WR-V", carImage: "./image/wrv.jpg" },
    { carName: "Toyota Urban Cruiser", carImage: "./image/urban_cruiser.jpg" },
    { carName: "Ford Freestyle", carImage: "./image/freestyle.jpg" },
    { carName: "MG Astor", carImage: "./image/astor.jpg" },
    { carName: "Tata Punch", carImage: "./image/punch.jpg" },
  ],
  pickup: [
    { carName: "Toyota Hilux", carImage: "./image/hilux.jpg" },
    { carName: "Ford Ranger", carImage: "./image/ranger.jpg" },
    { carName: "Isuzu D-Max V-Cross", carImage: "./image/dmax.jpg" },
    { carName: "Mahindra Bolero Camper", carImage: "./image/camper.jpg" },
    { carName: "Tata Yodha Pickup", carImage: "./image/yodha.jpg" },
    { carName: "Jeep Gladiator", carImage: "./image/gladiator.jpg" },
    { carName: "Nissan Navara", carImage: "./image/navara.jpg" },
    { carName: "Mitsubishi L200", carImage: "./image/l200.jpg" },
    { carName: "Chevrolet Colorado", carImage: "./image/colorado.jpg" },
    { carName: "GMC Sierra", carImage: "./image/sierra.jpg" },
  ],
  convertible: [
    { carName: "Mazda MX-5 Miata", carImage: "./image/miata.jpg" },
    { carName: "BMW Z4", carImage: "./image/z4.jpg" },
    { carName: "Porsche Boxster", carImage: "./image/boxster.jpg" },
    { carName: "Audi A5 Cabriolet", carImage: "./image/a5.jpg" },
    { carName: "Mercedes-Benz C-Class Cabriolet", carImage: "./image/cclass.jpg" },
    { carName: "Jaguar F-Type Convertible", carImage: "./image/ftype.jpg" },
    { carName: "Chevrolet Camaro Convertible", carImage: "./image/camaro.jpg" },
    { carName: "Ford Mustang Convertible", carImage: "./image/mustang.jpg" },
    { carName: "Ferrari Portofino", carImage: "./image/portofino.jpg" },
    { carName: "Lexus LC Convertible", carImage: "./image/lc.jpg" },
  ],
};
