export const carData = {
  hatchback: [
    "Maruti Suzuki Swift",
    "Hyundai i20",
    "Tata Altroz",
    "Maruti Suzuki Baleno",
    "Hyundai Grand i10 Nios",
    "Honda Jazz",
    "Volkswagen Polo",
    "Ford Figo",
    "Renault Kwid",
    "Tata Tiago",
  ],
  sedan: [
    "Honda City",
    "Maruti Suzuki Dzire",
    "Hyundai Verna",
    "Skoda Rapid",
    "Toyota Yaris",
    "Volkswagen Vento",
    "Tata Tigor",
    "Honda Amaze",
    "Hyundai Aura",
    "Skoda Slavia",
  ],
  suv: [
    "Hyundai Creta",
    "Kia Seltos",
    "Tata Nexon",
    "Mahindra XUV700",
    "Maruti Suzuki Vitara Brezza",
    "Toyota Fortuner",
    "Ford EcoSport",
    "MG Hector",
    "Mahindra Thar",
    "Renault Duster",
  ],
  mpv: [
    "Toyota Innova Crysta",
    "Maruti Suzuki Ertiga",
    "Mahindra Marazzo",
    "Renault Triber",
    "Kia Carens",
    "Mahindra Xylo",
    "Maruti Suzuki XL6",
    "Honda BR-V",
    "Datsun GO+",
    "Toyota Vellfire",
  ],
  ev: [
    "Tata Nexon EV",
    "MG ZS EV",
    "Hyundai Kona Electric",
    "Tata Tigor EV",
    "Mahindra eVerito",
    "BYD e6",
    "Jaguar I-PACE",
    "Audi e-tron",
    "Mercedes-Benz EQC",
    "Nissan Leaf",
  ],
  luxury: [
    "Mercedes-Benz S-Class",
    "BMW 7 Series",
    "Audi A8",
    "Jaguar XJ",
    "Lexus LS",
    "Volvo S90",
    "Porsche Panamera",
    "Bentley Continental GT",
    "Rolls-Royce Ghost",
    "Maserati Quattroporte",
  ],
  sports: [
    "Porsche 911",
    "Chevrolet Corvette",
    "Ford Mustang",
    "Audi R8",
    "Nissan GT-R",
    "BMW M4",
    "Ferrari 488",
    "Lamborghini Huracan",
    "Aston Martin Vantage",
    "McLaren 720S",
  ],
  crossover: [
    "Hyundai Venue",
    "Kia Sonet",
    "Nissan Kicks",
    "Maruti Suzuki S-Cross",
    "Renault Kiger",
    "Honda WR-V",
    "Toyota Urban Cruiser",
    "Ford Freestyle",
    "MG Astor",
    "Tata Punch",
  ],
  pickup: [
    "Toyota Hilux",
    "Ford Ranger",
    "Isuzu D-Max V-Cross",
    "Mahindra Bolero Camper",
    "Tata Yodha Pickup",
    "Jeep Gladiator",
    "Nissan Navara",
    "Mitsubishi L200",
    "Chevrolet Colorado",
    "GMC Sierra",
  ],
  convertible: [
    "Mazda MX-5 Miata",
    "BMW Z4",
    "Porsche Boxster",
    "Audi A5 Cabriolet",
    "Mercedes-Benz C-Class Cabriolet",
    "Jaguar F-Type Convertible",
    "Chevrolet Camaro Convertible",
    "Ford Mustang Convertible",
    "Ferrari Portofino",
    "Lexus LC Convertible",
  ],
};
